import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../layout/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Durgam Devi Sharam Prabhadye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Header>hi</Header>
      </div>
    </div>
  )
}
